<a href="https://colab.research.google.com/github/VoznesenskayaV/LabOP/blob/main/Worshop_2_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np
print("Версия Numpy: ", np.__version__)

Версия Numpy:  1.23.5


2) Создать нулевой вектор размера 10

In [2]:
zero_vector = np.zeros(10)
print(zero_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [4]:
seven_vector = np.full(7, 7)
print(seven_vector)

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [5]:
even_vector = np.arange(10, 101, 2)
print(even_vector)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [9]:
random_array = np.random.randint(1, 101, 10)
rev_array = random_array[::-1]
print("Исходный массив: ", random_array)
print("Разворот массива: ", rev_array)

Исходный массив:  [71 12 16 51 74 40 30 10 70 28]
Разворот массива:  [28 70 10 30 40 74 51 16 12 71]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [11]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [12]:
matrix_2 = np.zeros((4, 4), dtype=int)
for i in range(3):
  matrix_2[i, i+1] = 1
print(matrix_2)

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [13]:
matrix = np.full((4, 4), 7, dtype=int)
for i in range(4):
    matrix[i, i] = i + 1
print(matrix)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [15]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [23]:
matrix = np.random.randint(0, 10, size=(10, 10))
row_means = matrix.mean(axis=1, keepdims=True)
matrix_normalized = matrix - row_means

print("Исходная матрица:")
print(matrix)

print("\nМатрица после вычитания среднего:")
print(matrix_normalized)

Исходная матрица:
[[3 2 5 7 6 2 4 1 8 5]
 [0 6 8 1 1 7 6 5 0 0]
 [9 2 6 6 6 1 8 0 7 2]
 [2 4 7 6 7 5 3 8 6 7]
 [3 4 1 6 8 5 1 7 6 2]
 [5 3 6 0 5 0 5 2 3 0]
 [4 6 4 5 8 8 6 9 2 8]
 [2 5 2 7 8 5 2 9 4 0]
 [9 1 3 1 4 6 1 4 3 7]
 [3 1 8 0 8 2 4 0 1 8]]

Матрица после вычитания среднего:
[[-1.3 -2.3  0.7  2.7  1.7 -2.3 -0.3 -3.3  3.7  0.7]
 [-3.4  2.6  4.6 -2.4 -2.4  3.6  2.6  1.6 -3.4 -3.4]
 [ 4.3 -2.7  1.3  1.3  1.3 -3.7  3.3 -4.7  2.3 -2.7]
 [-3.5 -1.5  1.5  0.5  1.5 -0.5 -2.5  2.5  0.5  1.5]
 [-1.3 -0.3 -3.3  1.7  3.7  0.7 -3.3  2.7  1.7 -2.3]
 [ 2.1  0.1  3.1 -2.9  2.1 -2.9  2.1 -0.9  0.1 -2.9]
 [-2.   0.  -2.  -1.   2.   2.   0.   3.  -4.   2. ]
 [-2.4  0.6 -2.4  2.6  3.6  0.6 -2.4  4.6 -0.4 -4.4]
 [ 5.1 -2.9 -0.9 -2.9  0.1  2.1 -2.9  0.1 -0.9  3.1]
 [-0.5 -2.5  4.5 -3.5  4.5 -1.5  0.5 -3.5 -2.5  4.5]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [22]:
matrix = np.random.randint(0, 10, size=(10, 10))
column_medians = np.median(matrix, axis=0, keepdims=True)
matrix_normalized = matrix - column_medians

print("Исходная матрица:")
print(matrix)

print("\nМатрица после вычитания медианы:")
print(matrix_normalized)

Исходная матрица:
[[8 4 2 5 1 8 9 4 8 9]
 [7 8 2 8 9 2 1 1 7 9]
 [6 0 5 2 9 5 5 7 6 1]
 [0 3 2 8 3 6 9 5 4 6]
 [1 5 2 6 7 8 5 9 4 3]
 [2 2 2 2 7 5 6 7 3 3]
 [3 5 7 0 6 4 6 0 5 3]
 [4 8 8 7 7 6 7 2 6 2]
 [9 1 8 8 9 3 9 9 7 0]
 [4 8 4 8 6 0 1 6 1 0]]

Матрица после вычитания медианы:
[[ 4.  -0.5 -1.  -1.5 -6.   3.   3.  -1.5  2.5  6. ]
 [ 3.   3.5 -1.   1.5  2.  -3.  -5.  -4.5  1.5  6. ]
 [ 2.  -4.5  2.  -4.5  2.   0.  -1.   1.5  0.5 -2. ]
 [-4.  -1.5 -1.   1.5 -4.   1.   3.  -0.5 -1.5  3. ]
 [-3.   0.5 -1.  -0.5  0.   3.  -1.   3.5 -1.5  0. ]
 [-2.  -2.5 -1.  -4.5  0.   0.   0.   1.5 -2.5  0. ]
 [-1.   0.5  4.  -6.5 -1.  -1.   0.  -5.5 -0.5  0. ]
 [ 0.   3.5  5.   0.5  0.   1.   1.  -3.5  0.5 -1. ]
 [ 5.  -3.5  5.   1.5  2.  -2.   3.   3.5  1.5 -3. ]
 [ 0.   3.5  1.   1.5 -1.  -5.  -5.   0.5 -4.5 -3. ]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [24]:
matrix = np.random.randint(0, 10, size=(5, 5))
row_max = matrix.max(axis=1, keepdims=True)
row_min = matrix.min(axis=1, keepdims=True)
matrix_extended = np.hstack((matrix, row_max, row_min))

print("Исходная матрица:")
print(matrix)

print("\nМатрица с максимумами и минимумами по строкам:")
print(matrix_extended)

Исходная матрица:
[[8 0 4 1 9]
 [8 2 0 7 0]
 [9 7 1 9 8]
 [2 8 4 2 8]
 [5 5 9 5 1]]

Матрица с максимумами и минимумами по строкам:
[[8 0 4 1 9 9 0]
 [8 2 0 7 0 8 0]
 [9 7 1 9 8 9 1]
 [2 8 4 2 8 8 2]
 [5 5 9 5 1 9 1]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [30]:
vector = np.arange(1, 52)
# Нечетные и четные числа
odd_vector = vector[vector % 2 == 1]
even_vector = vector[vector % 2 == 0]

# Меняем размерности векторов, получаем 2 матрицы
odd_matrix = odd_vector[:25].reshape(5, 5)
even_matrix = even_vector[:25].reshape(5, 5)

odd_max = odd_matrix.max(axis=1, keepdims=True)
odd_min = odd_matrix.min(axis=1, keepdims=True)
even_max = even_matrix.max(axis=1, keepdims=True)
even_min = even_matrix.min(axis=1, keepdims=True)

# Матрицы с максимумами и минимумами (размер 5x2)
max_min_matrix = np.hstack((odd_max, odd_min, even_max, even_min))

# Находим произведение матриц
product_matrix = np.dot(odd_matrix, even_matrix)

# Находим обратную матрицу произведения
try:
    inverse_matrix = np.linalg.inv(product_matrix)
except np.linalg.LinAlgError:
    inverse_matrix = "Обратная матрица не существует"

print("Матрица нечетных чисел:")
print(odd_matrix)

print("\nМатрица четных чисел:")
print(even_matrix)

print("\nМатрица с максимумами и минимумами:")
print(max_min_matrix)

print("\nПроизведение матриц:")
print(product_matrix)

print("\nОбратная матрица произведения:")
print(inverse_matrix)

Матрица нечетных чисел:
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]

Матрица четных чисел:
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]

Матрица с максимумами и минимумами:
[[ 9  1 10  2]
 [19 11 20 12]
 [29 21 30 22]
 [39 31 40 32]
 [49 41 50 42]]

Произведение матриц:
[[ 750  800  850  900  950]
 [1850 2000 2150 2300 2450]
 [2950 3200 3450 3700 3950]
 [4050 4400 4750 5100 5450]
 [5150 5600 6050 6500 6950]]

Обратная матрица произведения:
Обратная матрица не существует


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [34]:
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1  # Нечетные строки, четные столбцы
matrix[::2, 1::2] = 1  # Четные строки, нечетные столбцы
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
